package com.briup.cms.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.id
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.code
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.name
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.id
     *
     * @return the value of cms_category.id
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.id
     *
     * @param id the value for cms_category.id
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.code
     *
     * @return the value of cms_category.code
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.code
     *
     * @param code the value for cms_category.code
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.name
     *
     * @return the value of cms_category.name
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.name
     *
     * @param name the value for cms_category.name
     *
     * @mbg.generated Tue Feb 25 23:37:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}