package com.briup.cms.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer.id
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer.username
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer.password
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer.id
     *
     * @return the value of cms_customer.id
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer.id
     *
     * @param id the value for cms_customer.id
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer.username
     *
     * @return the value of cms_customer.username
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer.username
     *
     * @param username the value for cms_customer.username
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer.password
     *
     * @return the value of cms_customer.password
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer.password
     *
     * @param password the value for cms_customer.password
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}