package com.briup.cms.model;

public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_link.id
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_link.name
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_link.url
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_link.id
     *
     * @return the value of cms_link.id
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_link.id
     *
     * @param id the value for cms_link.id
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_link.name
     *
     * @return the value of cms_link.name
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_link.name
     *
     * @param name the value for cms_link.name
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_link.url
     *
     * @return the value of cms_link.url
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_link.url
     *
     * @param url the value for cms_link.url
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}