package com.briup.cms.mapper;

import com.briup.cms.model.Customer;
import com.briup.cms.model.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByPrimaryKey(Customer record);
}