package com.briup.cms.mapper;

import com.briup.cms.model.Title;
import com.briup.cms.model.TitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    long countByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int deleteByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int insert(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int insertSelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    List<Title> selectByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    Title selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByExample(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByPrimaryKeySelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_title
     *
     * @mbg.generated Tue Feb 25 23:39:18 CST 2020
     */
    int updateByPrimaryKey(Title record);
}